//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imdbtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_data
    {
        public int id { get; set; }
        public string movie_name { get; set; }
        public Nullable<double> movie_rating { get; set; }
        public Nullable<System.DateTime> movie_release_date { get; set; }
        public Nullable<int> movie_duration { get; set; }
        public string movie_description { get; set; }
    }
}
